# Generated by Django 5.0 on 2024-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
