# Generated by Django 5.0 on 2024-01-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_is_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_child',
        ),
    ]
