# Generated by Django 5.0 on 2024-01-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_productvariant_attribute_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
