# Generated by Django 5.0 on 2024-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_author_about_authour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about_authour',
            field=models.TextField(blank=True, null=True),
        ),
    ]
