# Generated by Django 5.0 on 2024-01-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_author_about_authour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
