# Generated by Django 5.0 on 2024-01-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additonal_images',
            field=models.ImageField(null=True, upload_to='photos/product-variant/additional_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
