# Generated by Django 5.0 on 2024-01-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_additonal_images_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additonal_images',
        ),
    ]
