# Generated by Django 5.0 on 2024-01-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_publication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
