# Generated by Django 5.0 on 2024-01-16 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additonal_images',
            field=models.ImageField(null=True, upload_to='photos/product-variant/additional_images'),
        ),
        migrations.CreateModel(
            name='AdditionalProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/product-variant/additional-images')),
                ('is_active', models.BooleanField(default=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_product_images', to='store.product')),
            ],
        ),
    ]
