# Generated by Django 5.0 on 2024-01-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_additionalproductimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalproductimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product-variant/additional-images'),
        ),
    ]
