# Generated by Django 5.0 on 2024-01-16 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_additionalproductimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalproductimages',
            name='product_variant',
        ),
        migrations.AlterField(
            model_name='additionalproductimages',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/product-variant/additional-images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additonal_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_product_images', to='store.additionalproductimages'),
        ),
    ]
