# Generated by Django 5.0 on 2024-01-16 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_additionalproductimages_product_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additonal_images',
        ),
        migrations.AddField(
            model_name='additionalproductimages',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_product_images', to='store.product'),
        ),
    ]
