# Generated by Django 5.0 on 2024-01-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_product_additonal_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalproductimages',
            old_name='product_variant',
            new_name='product',
        ),
    ]
