# Generated by Django 5.0 on 2024-01-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_rename_product_variant_additionalproductimages_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalProductImages',
        ),
    ]
