# Generated by Django 5.0 on 2024-01-16 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_delete_additionalproductimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_books', to='store.publication'),
        ),
    ]
