# Generated by Django 5.0 on 2024-01-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_author_author_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='about_authour',
            new_name='about_author',
        ),
    ]
