# Generated by Django 5.0 on 2024-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_rename_about_authour_author_about_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
