# Generated by Django 5.0 on 2024-01-22 13:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_language_remove_productvariant_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variant_slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('thumbnail_image', models.ImageField(upload_to='photos/product-variant/thumbnail')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_translated', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.language')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more_details', to='store.product')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_books', to='store.publication')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_books', to='store.author')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/product-variant/additional-images')),
                ('is_active', models.BooleanField(default=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_product_images', to='store.productvariant')),
            ],
        ),
    ]
