# Generated by Django 5.0.1 on 2024-01-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_productvariant_additionalproductimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
