# Generated by Django 5.0.1 on 2024-01-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='translator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_books', to='store.author'),
        ),
    ]
