# Generated by Django 5.0.1 on 2024-01-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_alter_productvariant_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_books', to='store.author'),
        ),
    ]
