# Generated by Django 5.0.1 on 2024-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_alter_productvariant_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product_variant_slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
