# Generated by Django 5.0.1 on 2024-01-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_alter_productvariant_product_variant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='is_translated',
            field=models.BooleanField(default=False),
        ),
    ]
