# Generated by Django 5.0.1 on 2024-01-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_alter_productvariant_is_translated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='is_translated',
        ),
        migrations.AddField(
            model_name='product',
            name='is_translated',
            field=models.BooleanField(default=False),
        ),
    ]
