# Generated by Django 5.0.1 on 2024-02-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_remove_productvariant_is_translated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalproductimages',
            name='image',
            field=models.ImageField(upload_to='photos/product-variant/additional-images/{product_name}/{filename}'),
        ),
    ]
