# Generated by Django 5.0.1 on 2024-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_additionalproductimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalproductimages',
            name='image',
            field=models.ImageField(upload_to='photos/product-variant/additional-images/{filename}'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='thumbnail_image',
            field=models.ImageField(upload_to='photos/product-variant/thumbnail/{product.product_name}/{filename}'),
        ),
    ]
