# Generated by Django 5.0.1 on 2024-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_additionalproductimages_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_discount',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='pro_discount',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
