# Generated by Django 5.0.1 on 2024-02-14 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_alter_category_cat_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
