# Generated by Django 5.0 on 2024-01-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('unblocked', 'Unblocked')], default='active', max_length=10),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
