# Generated by Django 5.0.1 on 2024-02-02 09:54

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=adminapp.models.upload_path),
        ),
    ]
