# Generated by Django 5.0.1 on 2024-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='country',
            field=models.CharField(choices=[('IN', 'India')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam')], max_length=50),
        ),
    ]
