# Generated by Django 5.0.1 on 2024-02-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_coupon_verify_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
