# Generated by Django 5.0.1 on 2024-03-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_coupon_is_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_theme_logo', models.ImageField(upload_to='photos/logo/{filename}')),
                ('logo', models.ImageField(upload_to='photos/logo/{filename}')),
            ],
        ),
    ]
