# Generated by Django 5.0.1 on 2024-03-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_sitelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=50, null=True, unique=True)),
                ('dark_theme_logo', models.ImageField(upload_to='photos/logo/{filename}')),
                ('logo', models.ImageField(upload_to='photos/logo/{filename}')),
            ],
        ),
        migrations.DeleteModel(
            name='SiteLogo',
        ),
    ]
