# Generated by Django 5.0.1 on 2024-03-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_siteinfo_delete_sitelogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='refferal_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
