# Generated by Django 5.0.1 on 2024-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_newuser_refferal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
