# Generated by Django 5.0.1 on 2024-02-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Stripe', 'Stripe')], default='Cash on delivery', max_length=200),
        ),
    ]
