# Generated by Django 5.0.1 on 2024-02-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_payment_is_paid_remove_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_signature',
        ),
    ]
