# Generated by Django 5.0.1 on 2024-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('shipping', 'shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return initiated', 'Return initiated'), ('Returned', 'Returned')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_product_status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('shipping', 'shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return initiated', 'Return initiated'), ('Returned', 'Returned')], default='New', max_length=50),
        ),
    ]
