# Generated by Django 5.0.1 on 2024-02-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_status_order_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_product_status',
        ),
    ]
