# Generated by Django 5.0.1 on 2024-02-21 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_coupon_is_expired'),
        ('orders', '0012_remove_orderproduct_order_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.coupon'),
        ),
    ]
